### ISSUE TITLE
'立夏', '乙巳', '庚申', '戊寅'

### ISSUE THREAD

**Issue by Juan-hwt** [kentang2017/kinliuren#6]
Traceback (most recent call last):
  File "c:\Users\26856\cp\liuren.py", line 20, in <module>
    t = kinliuren.Liuren('立夏', '乙巳', '庚申', '戊寅').result(0)
  File "E:\Python\Python39\lib\site-packages\kinliuren\kinliuren.py", line 1251, in result
    guiren_order_list_2 = self.guiren_order_list(num)
  File "E:\Python\Python39\lib\site-packages\kinliuren\kinliuren.py", line 1233, in guiren_order_list
    ju = ju_three_pass[0][0]
TypeError: 'NoneType' object is not subscriptable

其他都没问题，就这一组有问题

**Comment by kentang2017** [comment]
修正了, 請試試。

**Comment by Juan-hwt** [comment]
ok  all is running      good job
